### ISSUE TITLE
How does rustfmt work with eclipse corrosion?

### ISSUE THREAD

**Issue by adellanna** [eclipse/corrosion#161] opened 2018-10-26 14:05 UTC
Is there any way to apply automatic rustfmt code formatting (or cargo fmt formatting) using Eclipse Corrosion like the old RustDT pluging did?

If I format my code using right-click-to-project->Source->Format, eclipse doesn't use rustfmt.
If I just save my source it doesn't format the code and if I check on Windows->Preferences-> Rust->Text editor, it just says: "see Text editors for general text editor setting"

Am I missing something?

**Comment by Boereck** [comment] 2018-10-26 16:34
Hi, when you are in a rust file, you can press "Ctrl+Shift+F" to format the file via RLS (which will use rustfmt). Or right click in the open file and select the "Format" context menu item. I don't know where the entry in the project context menu is coming from, but I don't think this formatting option is coming from corrosion. I don't think formatting a complete project is not supported at this time.

I think it would be possible to implement an option that would allow formatting on save. Unfortunately the generic editor (which is the basis for the rust tooling) does and will not support simple save actions (see [this](https://bugs.eclipse.org/bugs/show_bug.cgi?id=522744) bug). So the implementation would be a bit more involving.

**Comment by norru** [comment] 2018-11-03 18:36
Formatting in Eclipse handled by the RLS, which in turn uses `rustfmt` under the hood. Ctrl+shift+F should be basically triggering a `rustfmt` on the current file.

**Comment by adellanna** [comment] 2018-11-05 17:08
Hi @Boereck,

I'm sorry but "Ctrl+Shift+F" or right click in the open file and select the "Format" context menu item 
triggers the eclipse formatting not the RLS/rustfmt one.
I noticed that because after I format, the code is tab idented instead of space idented like it should be using rustfmt.

Are there any plans to support a complete rust project formatting in corrosion?

**Comment by norru** [comment] 2018-11-05 20:34
This is what happens in RLS when I hit `Ctrl+Shift+F`:

```

**Comment by norru** [comment] 2018-11-05 20:38
I supect that RLS has a different set of defaults than the "vanilla" `rustfmt` (which might be a bug in itself, but I would not be surprised if it were "as designed" as many other weird things in RLS).

RLS in Eclipse seems to be honoring the `.rustfmt.toml` settings in the root of the project though.

**Comment by Boereck** [comment] 2018-11-06 19:31
@adellanna Corrosion does not have an own formatter for Rust sources. So the omitted replacement of tabs to spaces, as @norru said, must somehow be an omission by the RLS or how it uses rustfmt. I cannot reproduce the issue. Maybe open an issue on the [RLS](https://github.com/rust-lang-nursery/rls) or ask on the Rust [user forum](https://users.rust-lang.org/) or ask on the [IRC channels](https://www.rust-lang.org/en-US/community.html#irc-channels) if this is a known issue and if there is a way to fix or work around the issue.

There is currently no plan (I know of) to implement bulk formatting or auto formatting on save. But these are very valid feature requests. I myself would be interested in auto-format on save, so these may come at some point. We can keep this issue open to track progress.

**Comment by norru** [comment] 2018-11-06 20:50
I think it's a "feature" in RLS.

**Comment by norru** [comment] 2018-11-09 21:30
@Boereck, @adellanna In fact, it's actually Corrosion's (possibly TM4E's component) fault.

It does look like that the settings in **Preferences -> Editors -> Text Editors -> Insert spaces for tabs** and **Print margin column** override the default RLS/rustfmt settings (these settings are probably being passed down to RLS via LSP).

I think those two settings should **not** influence the way RLS and `rustfmt` do the formatting, as there clearly says "**Insert** space for tabs** and not "Replace tabs with spaces when reformatting".

**Comment by norru** [comment] 2018-11-20 12:00
Looking at the logs, the RLS formatter invocation does override the default `rustfmt` settings with ones set in the **Preferences**.
```
LSP4E to org.eclipse.corrosion.rls:{"jsonrpc":"2.0","id":"17","method":"textDocument/formatting","params":{"textDocument":{"uri":"file:///home/norru/Projects/ivt/parallax_testbed/src/main.rs"},"options":{"tabSize":4,"insertSpaces":false}}}
```

**Comment by norru** [comment] 2018-11-21 22:33
@adellanna does this answer your question?

**Comment by norru** [comment] 2019-01-02 22:58
Added explanation as *rustfmt caveat* in https://github.com/eclipse/corrosion/pull/203/commits @adellanna @mickaelistria: shall we close this?

**Comment by mickaelistria** [comment] 2019-01-02 22:59
@norru Thanks, I agree this document and answer cover the initial request in the ticket. If someone wants to further improve integration with rustfmt, they're welcome to put the enhancement proposals in new tickets.

**Closed by mickaelistria** 2019-01-02 22:59 UTC
