### ISSUE TITLE
"Out of order change" error

### ISSUE THREAD

**Issue by norru** [eclipse/corrosion#246] opened 2019-04-18 16:40 UTC
I am getting the following error quite often while ~~editing~~ formatting code with `Ctrl+Shift+F`

"Out of order change in [...].rs"

![image](https://user-images.githubusercontent.com/889291/56809389-3bec5980-6823-11e9-97ed-cc7cab136958.png)

**Comment by norru** [comment] 2019-06-11 16:09
Upgrading to Eclipse 2019-06 and latest Corrosion snapshot fixes the problem.

**Comment by norru** [comment] 2019-07-04 10:53
Getting the problem again in Eclipse 2019-06 release.

**Comment by norru** [comment] 2020-12-30 17:52
Still open in 2020-12

**Comment by domibay-hugo** [comment] 2021-01-11 15:18
This issue seems me to originate from an inappropiate use of the `rls` Service.
Analysing the system activity of the `rls` service during the lifetime of the _Eclipse_ Editor with the `strace` tool it turned out that **1 Main Thread** spawned **544 Worker Threads** in **60 min** of observation window.
The Main Thread accepting incoming requests:
```
$ cat strace_rls-3667_2021-01-11-1.txt|grep -i "read("|grep -i "content"|sort|uniq |sed -n 1,10p
3667  read(0, "Content-Length: 162\r\n\r\n{\"jsonrpc"..., 8192) = 376
3667  read(0, "Content-Length: 163\r\n\r\n{\"jsonrpc"..., 8192) = 186
3667  read(0, "Content-Length: 168\r\n\r\n{\"jsonrpc"..., 8192) = 376
3667  read(0, "Content-Length: 169\r\n\r\n{\"jsonrpc"..., 8192) = 192
3667  read(0, "Content-Length: 211\r\n\r\n{\"jsonrpc"..., 8192) = 234
3667  read(0, "Content-Length: 212\r\n\r\n{\"jsonrpc"..., 8192) = 235
3667  read(0, "Content-Length: 26099\r\n\r\n{\"jsonr"..., 8192) = 8192
3667  read(0, "Content-Length: 26911\r\n\r\n{\"jsonr"..., 8192) = 8192
3667  read(0, "Content-Length: 294\r\n\r\n{\"jsonrpc"..., 8192) = 2536
```
And spawned Worker Threads sending back the results:
```
$ cat strace_rls-3667_2021-01-11-1.txt|grep -i "write("|grep -i "content"|sort|uniq|sed -n 1,10p
10251 write(1, "Content-Length: 137\r\n\r\n", 23) = 23
10251 write(1, "Content-Length: 1445\r\n\r\n", 24) = 24
10251 write(1, "Content-Length: 380\r\n\r\n", 23) = 23
10251 write(1, "Content-Length: 559\r\n\r\n", 23) = 23
10252 write(1, "Content-Length: 137\r\n\r\n", 23) = 23
10252 write(1, "Content-Length: 143\r\n\r\n", 23 <unfinished ...>
10252 write(1, "Content-Length: 144\r\n\r\n", 23) = 23
10252 write(1, "Content-Length: 145\r\n\r\n", 23 <unfinished ...>
10266 write(1, "Content-Length: 137\r\n\r\n", 23) = 23
10266 write(1, "Content-Length: 380\r\n\r\n", 23) = 23
```
Each worker thread seems to compile the project with and to read the data structure outlay.

But taking into account that even the **Incremental Compilation Time** of _Rust_ is about **1 - 2 s** this architecture is not thought to be **Real Time** and thus is not suitable to be requested on each **Key Stroke**.
The results of the request might arrive long after the actual event and so it produces a **Desynchronization Error** as I understand it from the `rls` Source Code as other people have pointed out.

Other Programming Language Plugins have an **Inactivity Delay** which delays the **Parsing Requests** until the delay is fulfilled or a Autocompletion is requested.
On other Programming Language Plugins I have set this to **500 ms** to not pop up immediately.

On Save Events also the whole File can be rescanned to correct desynchronizations.

Often the Plugin keeps pointing out code errors during the development process long after the original code is already gone.

**Comment by domibay-hugo** [comment] 2021-01-11 15:54
When formatting the code with indentation it often produces garbage errors with erronous non existing functions like:
``` 
cannot find function `nonot_existing_function()` in this scope.

help: a function with similar name exists: `existing_function()` 
```
which seems me to indicate a desynchronization error due to partial updates.

Those errors also cannot be solved but only by whole editor restart.

**Comment by mickaelistria** [comment] 2021-01-11 16:01
@domibay-hugo Thanks for this useful analysis, I'm kind of relieved to see that this is a bug in RLS. Can you please open a bug to RLS about it? However, Corrosion will ultimately move to rust-analyzer when this become officially stable, so maybe it's more interesting to place effort in lobbying to have rust-analyzer as stable.

**Comment by domibay-hugo** [comment] 2021-01-12 08:32
@mickaelistria Thank you for taking interest in this issue.
I don't know if the `rust-analyzer` will provide actually **Real-Time** Results (response time < 10ms) but I think the best strategy for giving the best usability for your so essential Editor Plugin is not to rely on it and implement strategies that can mitigate **Response Delays** and **Desynchronization Issues**.

A good strategy could be, for example, to do a **complete Code Analysis** at the **OnSave Event**.

Also I think that a good Programming Language Support does not need to be **Real-Time** but it rather should be comprehensive and correct.
So, I think a configurable **Update Delay** is mostly acceptable.

**Comment by mickaelistria** [comment] 2021-01-12 08:41
The strategy of when to do code analysis is internal to rust-analyzer, not something we can nor aim to control in Corrosion.

**Comment by norru** [comment] 2021-01-12 09:38
To clarfy @domibay-hugo have you observed the *Eclipse* LSP client actually *sending* "real-time" requests to the RLS process (ie, one request per keystroke)? If this is the case the bug is in the LSP/Corrosion site, otherwise the bug is in RLS.

> A good strategy could be, for example, to do a complete Code Analysis at the OnSave Event.

A delayed/idle approach is fine. I don't want to have to explicitly save my code just to have a trivial syntax error reported. I'd end up saving every 3/5 seconds just to trigger a scan of the current file.

**Comment by norru** [comment] 2021-01-12 09:39
@mickaelistria last I heard is that `rust-analyzer` is not quite ready to replace RLS as yet (I'm waiting for it too!)

**Comment by mickaelistria** [comment] 2021-01-12 09:54
>  Eclipse LSP client actually sending "real-time" requests to the RLS process (ie, one request per keystroke)? If this is the case the bug is in the LSP/Corrosion site,

LSP4E sends a notification on every keystroke. It's conform to LSP and works for all language servers. If RLS cannot deal with it, then it means RLS is not behaving properly as defined by LSP specification.

> Last I heard is that rust-analyzer is not quite ready to replace RLS as yet,

When I posted about latest Corrosion release on Reddit, people were all telling how rust-analyzer is better and should be used instead. The only thing that prevents from moving is that the project is still declared as unstable on Cargo, and we don't really have the capacity to deal with projects that are still advertising themselves as unstable as it means we'll probably have a higher maintenance cost for some time.

**Comment by norru** [comment] 2021-01-12 10:00
> LSP4E sends a notification on every keystroke. It's conform to LSP and works for all language servers. If RLS cannot deal with it, then it means RLS is not behaving properly as defined by LSP specification.

Good to know! Interestingly, I wonder how the VSC plugin for Rust does this, perhaps they *do not* send very keystroke, or they would have encountered the same problem?

**Comment by domibay-hugo** [comment] 2021-01-12 10:36
The related issue [rls::actions: Out of order or duplicate change](https://github.com/rust-lang/rls/issues/1111) documents that with `rls`on _Sublime Text 3_ happens the same issue as well.

I think it's quite understandable because _Rust_ is not known for its swift **Compilation Time**.
A normal Compilation Time is about **1 - 2 s** and can go up to **5 s** if there are many changes.
```text
$ cargo build
   Compiling my_project v0.1.0 (/path/to/my-project)
    Finished dev [unoptimized + debuginfo] target(s) in 5.21s
```
and when some coding error is encountered it still takes **> 100ms**:
```text
$ date +"%s.%N" ; cargo build ; date +"%s.%N"
1610446822.961529668
   Compiling my_project v0.1.0 (/path/to/my-project)
error: expected expression, found `;`
   --> src/regex-api.rs:578:18
    |
578 |   let mut irs = -;
    |                  ^ expected expression

error: aborting due to previous error

error: could not compile `regex_api`.

To learn more, run the command again with --verbose.
1610446823.080178893
$ echo "scale=3; 23.080178893-22.961529668"|bc -l
.118649225
```
But when I'm editing and formatting the code changes are extremely fast and the response that arrives from the `rls` is already outdated which produces bizarre `function not found` errors as documented above.

Especially the errors pop up when indenting the code with `tab`s . For each tab I see a `out of order` Error.

So, the suggestion for a mitigation of the slow Response Time was to not to submit a request on each **Key Stroke** or to handle outdated responses the correct way which I think is even more challenging.
Just as in an **Autocomplete** on a **Web Site** you need to cancel former unresponded requests when submitting new ones.

**Comment by domibay-hugo** [comment] 2021-01-12 10:48
The official Project Documentation states:
[Debugging `rls`](https://github.com/rust-lang/rls/blob/master/debugging.md#project-issues)
> Project issues
> If a project has a lot of dependencies, initial indexing might take a long time. In general, initial indexing should take about the same time as a full compile of the project (usually a little less time, but that depends).
> 
> If the primary crate of a project is large, it probably won't work well with the RLS (too slow). Exactly what 'large' means here will depend on how fast your machine is and how tolerant of latency you are.

The expression "_tolerant of latency_" is especially directed to Client Applications.

**Comment by mickaelistria** [comment] 2021-01-12 10:53
I can understand a language being slow or even ignoring some requests in some cases when it's very busy with other things, but processing change events in the right order is a must have for LSP; alternative behaviours are bugs in the LS.

**Comment by norru** [comment] 2021-01-12 15:24
@domibay-hugo to clarify, the RLS plugin in Eclipse is based on a general-purpose, abstract LSP interface which can handle any Language Server, as long as the language server sticks to the LSP specification. If what you report is true, it means that RLS relies on the client application handling the case where it can't cope, which is not something that can or should be handled by the Eclipse plugin.

**Comment by domibay-hugo** [comment] 2021-01-13 10:03
With the instructions found in this post:
[Eclipse Corrosion RLS Logs](https://github.com/eclipse/corrosion/issues/186#issuecomment-447143434)
and the instructions about logging the `rls` activity found at:
[`rls` logs](https://github.com/rust-lang/rls/blob/master/debugging.md#logging)
I was able to reproduce and log the communication that lead to the issue under discussion.
You can see the communication logs in the _Console View_ and in the `org.eclipse.corrosion.rls.log` log file.

How to reproduce?
- Delete the indention from 6 lines of code
- Mark the 6 lines of code with the mouse
- Indent the 6 lines of code 5 times with `tab`

The file `org.eclipse.corrosion.rls.log` reports the following communication:
```
[t=1610529888395] LSP4E to org.eclipse.corrosion.rls:
Content-Length: 293


[t=1610529888395] LSP4E to org.eclipse.corrosion.rls:
{"jsonrpc":"2.0","method":"textDocument/didChange","params":{"textDocument":{"version":15,"uri":"file:///path/to/my_project/src/my-project-1.rs"},"contentChanges":[{"range":{"start":{"line":418,"character":0},"end":{"line":418,"character":0}},"rangeLength":0,"text":"  "}]}}
[t=1610529888395] org.eclipse.corrosion.rls to LSP4E:
{"jsonrpc":"2.0","method":"window/showMessage","params":{"message":"Out of order change in \"/path/to/my-project-1.rs\"","type":2}}
```
[org.eclipse.corrosion.rls_2021-01-13-2.log](https://github.com/eclipse/corrosion/files/5807822/org.eclipse.corrosion.rls_2021-01-13-2.log)

**Comment by domibay-hugo** [comment] 2021-01-13 11:21
I was also able to reproduce the bizarre Error Reports when formatting the code and opened a corresponding Issue with the _RLS_ Project:
[Unexpected Operator Error from _RLS_](https://github.com/rust-lang/rls/issues/1710)

**Comment by norru** [comment] 2021-01-13 11:48
Great work, @domibay-hugo, thanks a lot!

**Comment by akurtakov** [comment] 2022-07-13 10:13
Closing due to lack of interest from reporters to test it out. If you still experience the issue with latest version please reopen with details.

**Closed by akurtakov** 2022-07-13 10:13 UTC
