### ISSUE TITLE
Unable to debug rust programs

### ISSUE THREAD

**Issue by nibin** [eclipse/corrosion#93] opened 2018-06-29 07:47 UTC
Hi,
I downloaded eclipse photon release for mac. I tried to create a simple hello world project and wanted to see debugging options from eclipse. IDE was not able to hit the breakpoints but it printed the "hello world" message.

See the below flows

![screen shot 2018-06-29 at 12 42 43 am](https://user-images.githubusercontent.com/519723/42079927-edd02806-7b35-11e8-81a7-056dd0af31a4.png)
![screen shot 2018-06-29 at 12 43 09 am](https://user-images.githubusercontent.com/519723/42079933-f1d8e884-7b35-11e8-84da-39c471d732ac.png)
![screen shot 2018-06-29 at 12 43 26 am](https://user-images.githubusercontent.com/519723/42079942-f46ace8c-7b35-11e8-8c05-8ce607f06e98.png)
![screen shot 2018-06-29 at 12 47 42 am](https://user-images.githubusercontent.com/519723/42080002-1c11ee8e-7b36-11e8-92d6-d48e6f94cfac.png)

**Comment by akurtakov** [comment] 2018-06-29 07:53
So this is Mac OS ? I can see it from screenshots but to get your confirmation.
Is gdb installed on your machine and on your PATH ?

**Comment by nibin** [comment] 2018-06-29 08:16
Yes. This is macOS.
GDB is installed and available on PATH
![screen shot 2018-06-29 at 1 14 05 am](https://user-images.githubusercontent.com/519723/42081343-0d4c2640-7b3a-11e8-845e-11c1ad12c339.png)

**Comment by akurtakov** [comment] 2018-06-29 08:36
Corrosion relies on CDT GDB in order to understand better where the issue lays would you please create a Hello world C app and try to debug it. You may need to install CDT for that.

**Comment by LucasBullen** [comment] 2018-06-29 13:47
Thank you for the report @nibin, I have a Mac at home and can continue the debugging next week. If I'm unable to reproduce then I will ask for some extra help from you.

**Comment by nibin** [comment] 2018-06-29 18:00
Hi @akurtakov ,

I installed CDT on my eclipse photon instance. I wrote a simple hello world C program. I tried to debug this program and was not happening properly. I tried the steps mentioned in below links.

https://www.ics.uci.edu/~pattis/common/handouts/macmingweclipse/allexperimental/mac-gdb-install.html
https://www.thomasvitale.com/how-to-setup-gdb-and-eclipse-to-debug-c-files-on-macos-sierra/

In a nutshell, I had to do code signing of gdb. I did this and I am seeing a different problem with CDT.
When I try to debug a C program, it is not hitting the break points correctly and the gdb session is getting terminated.

![screen shot 2018-06-29 at 10 47 21 am](https://user-images.githubusercontent.com/519723/42106845-462955aa-7b8a-11e8-9596-d748373db9e0.png)
![screen shot 2018-06-29 at 10 47 37 am](https://user-images.githubusercontent.com/519723/42106850-48d21576-7b8a-11e8-9ddb-d748b73ac6a8.png)
![screen shot 2018-06-29 at 10 48 02 am](https://user-images.githubusercontent.com/519723/42106889-6321f874-7b8a-11e8-844e-f278a629463e.png)

My GDB params looks like below
![screen shot 2018-06-29 at 10 52 02 am](https://user-images.githubusercontent.com/519723/42106921-847bc59a-7b8a-11e8-9985-1152db230e85.png)

I also tried to do a rust debugging to see the issues. My configurations are shown below:
![screen shot 2018-06-29 at 10 53 15 am](https://user-images.githubusercontent.com/519723/42107131-1ac223c8-7b8b-11e8-868f-1033dcf024d4.png)
![screen shot 2018-06-29 at 10 53 31 am](https://user-images.githubusercontent.com/519723/42107135-202f270c-7b8b-11e8-8b0d-ab02ccdc160c.png)

When I right-click on project, and if I do "Debug As" > "Rust Project", it doesnt hit the breakpoint and prints the message.
![screen shot 2018-06-29 at 10 55 39 am](https://user-images.githubusercontent.com/519723/42107185-4bef6c8a-7b8b-11e8-937f-e1b31fc312ed.png)

If I explicitly click on a debug configuration as shown below and click on it, then I get a error dialog. 
![screen shot 2018-06-29 at 10 58 28 am](https://user-images.githubusercontent.com/519723/42107256-7e59a0a0-7b8b-11e8-8f8f-bb1d65c9753f.png)
![screen shot 2018-06-29 at 10 56 02 am](https://user-images.githubusercontent.com/519723/42107262-81da35e6-7b8b-11e8-9196-0a989bf8468c.png)

PS: I am still figuring out how to get CDT to do a proper debugging in macOS. Not sure whether it is broken in eclipse photon. I will take a vanilla CDT and check it out.

**Comment by nibin** [comment] 2018-06-29 18:13
I downloaded Eclipse (photon) CDT from below location.
http://www.eclipse.org/downloads/packages/eclipse-ide-cc-developers/photonr

I tried writing a simple C program and the debug was failing with same issue. It was not hitting the breakpoint and showing some arbitrary assembly. Also gdb session was getting terminated.

![screen shot 2018-06-29 at 11 10 35 am](https://user-images.githubusercontent.com/519723/42107760-5df0b63a-7b8d-11e8-8ca9-4a83d1bd734a.png)

**Comment by snuk182** [comment] 2018-07-11 16:05
Exactly the same on windows. GDB is installed.

**Comment by LucasBullen** [comment] 2018-07-25 19:05
Our debugging setup is a close clone of [RustDT](https://github.com/RustDT/RustDT)'s. It contains [warnings](https://github.com/RustDT/RustDT/blob/master/documentation/UserGuide.md#debugging) for Windows and Mac users that the default gdb does not work. It also includes instructions of workarounds: 

| **Windows note:** _Using Cygwin GDB doesn't work properly. The recommended way to debug in Windows is to use the GDB of [TDM-GCC](http://tdm-gcc.tdragon.net/), or the one of [mingw-w64](http://mingw-w64.org/)._ |
|----|

| **OS X note:** _The GDB that is included with OS X doesn't work properly. You'll need to install the latest GDB from Homebrew or Macports. See [this SO question](https://stackoverflow.com/questions/33162757/how-to-install-gdb-debugger-in-mac-osx-el-capitan) for more up-to-date information._ |
|----|

Would you be able to test with the workarounds?

**Comment by nibin** [comment] 2018-07-25 19:57
I did the same for mac. I have also added the comment related to gdb codesigning that was done [here](https://github.com/eclipse/corrosion/issues/93#issuecomment-401429443)

**Comment by anb0s** [comment] 2018-09-18 11:42
I've tried today with latest corrosion and rust from nightly and see the error under Debian 10.
Eclipse Photon with latest CDT installed and rust-gdb executable is there in terminal / console...
Run is working, but debugging shows error "Unable to launch Rust Project from selection. Program file does not exist". I've checked the program path and it's there...

**Comment by anb0s** [comment] 2018-09-18 12:34
It looks like an issue with relative program path. After deselect "Use default" and entering the absolute path to the executable the error changes to: "Unable to launch Rust Project from selection. Could not determine GBD version using command: rust-gdb --version".

From the command line:
```
rust-gdb --version
GNU gdb (Debian 8.1-4) 8.1
...

```

**Comment by norru** [comment] 2018-09-27 18:09
@anb0s I can debug on Debian with no issues, if I set up a Rust configuration with the following settings
```
Executable:
  ${project_loc}/target/debug/<name of your binary>
Working Direcotry (sic ;)
  ${project_loc}
```

In fact I just managed to debug a Rust program on windows by pretending it was a **C++ executable**

**Comment by mickaelistria** [comment] 2018-09-28 07:06
Please you open separate issues for different problems (typically each environment/gdb version could be a single issue). This one talks about too many distinct cases, it's hard to sort out what are the potential fixes or improvements.

**Comment by jjohnstn** [comment] 2018-09-28 16:41
If CDT debugging is not working for a C program, please post to the cdt-dev@eclipse.org list.  The debugging experts will help you with your set up for your particular system.

Regarding one of the errors showing a dialog reporting a null value: rust developers should look to ensure that the Launch Configuration delegate is not setting a launch property to null or failing to set a mandatory value.  See IGdbDebugPreferenceConstants.java, ICDTLaunchConfigurationConstants.java, and IGDBLaunchConfigurationConstants.java in the CDT sources.

**Comment by anb0s** [comment] 2018-10-03 11:17
@norru thanks, i will try the workarounds and report
@mickaelistria ok, i will create separate issues for different OS and other combinations

**Comment by anb0s** [comment] 2018-10-03 11:18
see #139 for Linux Arch (Manjaro) debug issues

**Comment by anb0s** [comment] 2018-10-03 11:55
@norru see #140 i've tried it after update of all tools and it works with Debian and GDB 8.1 now

**Comment by mickaelistria** [comment] 2018-11-21 20:08
@anb0s what's still remaining to do about this issue? Can we close it?

**Comment by anb0s** [comment] 2018-11-21 21:52
I do not see any issues with Linux OS (#139 and #140) anymore --> OK

Windows with MinGW GDB does not work without workarounds, see #138 and #149 

This one was for Mac, but i have no Mac machine for test... @nibin if it works it can be closed?

**Comment by mickaelistria** [comment] 2018-12-30 15:12
@justdak Do you think #201 could improve that?

**Comment by mickaelistria** [comment] 2019-01-02 16:53
Ok, so I'm closing this bug as #138 / #201 cover the remaining parts.
If anyone has some other issue than #138 with the debugger, please open a new dedicated ticket.

**Closed by mickaelistria** 2019-01-02 16:53 UTC
Labels: bug
