### ISSUE TITLE
Rust-Editor only syntax coloring

### ISSUE THREAD

**Issue by Krzmbrzl** [eclipse/corrosion#229] opened 2019-02-21 13:50 UTC
When opening a Rust-file inside eclipse with the corrosion plugin installed, I do not get any features except syntax highlighting. Whenever I am in the code and do Ctrl+Space it will tell me that there are no completion proposals. If I do the same in empty space I get a few entries in it but nothing too helpful.

Also I do not get any error-markers no matter what I type in the source code (There are no problems in the problems view either).

I am not quite sure if it may be a problem that all Rust files are being opened in the `Generic Text Editor` but I couldn't find a Rust-editor so I guess this is the correct one?

I am using eclipse version `2018-09` and Corrosion v0.3.0

![content-assist](https://user-images.githubusercontent.com/12751591/53173386-d8a63700-35e7-11e9-8b06-f4f61d4e9d9a.png)

**Comment by mickaelistria** [comment] 2019-02-21 13:53
Can you please check the error log in <workspace>/.metadata/.log ?

**Comment by Krzmbrzl** [comment] 2019-02-21 15:20
It says
```
!MESSAGE RLS settings for Corrosion path not set.
```
Before that it said that it couldn't find the setting at the path specified in the settings (It was set to `/home/<username>/.cargo/rls.conf`). I googled and found #186  in which you wrote

> the `.cargo/rls.conf` file contains the startup settings for the `rls` and it is optional. If you don't have one, Corrosion will ignore it and guess some sensible (!) defaults.

So I thought that maybe removing that preference might help. But obviously it doesn't ^^

**Comment by Krzmbrzl** [comment] 2019-02-21 15:30
Okay I just tried it with Eclipse `2018-12` and now it seems to be working. However now it shows me errors where there are none.

The project compiles just fine but it says it can't find an import. (The import is from within the current project. All external imports (std-lib) are resolved properly. Is there a setting for the include-path?

**Comment by norru** [comment] 2019-02-27 15:47
> Is there a setting for the include-path?

All `rustc`'s path management are done via `cargo` and `rustup` within RLS.

**Comment by theDragonFire** [comment] 2019-03-07 21:17
> The project compiles just fine but it says it can't find an import. (The import is from within the current project. All external imports (std-lib) are resolved properly.

Try restarting it. For some reason, I've found that you have to restart Eclipse after you use `extern crate current-project` in order for it to load.

**Comment by mickaelistria** [comment] 2019-03-07 21:21
> For some reason, I've found that you have to restart Eclipse after you use extern crate current-project in order for it to load.

That's interesting. Can you please create a dedicated issue about this ?

**Comment by mickaelistria** [comment] 2019-06-12 14:14
Can you please try with the 2019-06 release candidate: https://www.eclipse.org/downloads/packages/release/2019-06/rc1

**Comment by mickaelistria** [comment] 2019-07-04 08:46
Cannot reproduce and no news for 3 months, closing.

**Closed by mickaelistria** 2019-07-04 08:46 UTC

**Comment by sleeply4cat** [comment] 2020-10-27 22:29
Still have this issue with Eclipse IDE for Rust Developers (2020-09 (4.17.0))
Just downloaded and installed Rust & Eclipse from the official sites.
![Screenshot from 2020-10-28 01-25-56](https://user-images.githubusercontent.com/37955805/97368790-b71d4880-18bc-11eb-9fac-90c293c1e804.png)

**Comment by mickaelistria** [comment] 2020-11-01 17:52
@sleeply4cat Have you gone through the previous discussion on this ticket? Do you have some more info to share regarding the previous comments/questions?
