### ISSUE TITLE
Opening a "big" file will constantly freeze the whole IDE

### ISSUE THREAD

**Issue by ctron** [eclipse/corrosion#255] opened 2019-06-25 19:47 UTC
Having a big Rust file:

~~~
[root@8e152878163b build]# wc esp32-sys/src/bindings.rs
  25462  136865 1047352 esp32-sys/src/bindings.rs
~~~

The whole Eclipse IDE constantly freezes. Closing the editor of this file reverts the IDE back into a stable state.

**Comment by mickaelistria** [comment] 2019-06-25 19:48
Can you run a `jstack` when you see the freeze and share the output here?

**Comment by ctron** [comment] 2019-06-26 08:42
I tried to reproduce it on Linux. I didn't see the issue there, maybe it is a Windows issue. I will try again this evening, when I have access the Windows machine.

**Comment by ctron** [comment] 2019-06-26 17:57
After starting up everything seemed fine for a while. But when I made a change in the big file, it happened again. Here are two stacks I captured with a bit of delay: 

* [stack.txt](https://github.com/eclipse/corrosion/files/3331362/stack.txt)
* [stack2.txt](https://github.com/eclipse/corrosion/files/3331363/stack2.txt)

**Comment by mickaelistria** [comment] 2019-06-27 08:04
Reported upstream as https://bugs.eclipse.org/bugs/show_bug.cgi?id=548697
As a workaround, you can close the "Outline" view as it seems to be where the performance issue is "implemented".

**Comment by mickaelistria** [comment] 2019-09-22 20:50
@ctron

> Having a big Rust file...

How can I get this file? It looks like it's some generated file. Can you please post it or describe steps to generate it, or whatever is necessary to reproduce the issue with this file?

**Comment by mickaelistria** [comment] 2019-09-24 18:39
Closing as it's tracked upstream in LSP4E.
Let's continue discussion in https://bugs.eclipse.org/bugs/show_bug.cgi?id=548697

**Closed by mickaelistria** 2019-09-24 18:39 UTC
Labels: upstream-eclipse

**Comment by ctron** [comment] 2019-09-30 07:56
I think this should work: [big-rust-file.zip](https://github.com/eclipse/corrosion/files/3669448/big-rust-file.zip)

**Comment by mickaelistria** [comment] 2019-09-30 20:13
Seems fine locally. Please try installing latest LSP4E build from http://download.eclipse.org/lsp4e/snapshots .

**Comment by ctron** [comment] 2019-10-01 07:12
Did you try on Windows? As it was ok on Linux, but not on Windows. If I don't forget, then I can try this evening with Windows again.

**Comment by mickaelistria** [comment] 2019-10-01 08:48
No, I didn't try on Windows and don't have Windows available to try it (nor really much motivation to invest time in Windows specific issues to be honest).

**Comment by ctron** [comment] 2019-10-06 12:23
Just tried this again on Windows. Rust 1.38 and Eclipse 2019-09. And it still is an issue.
