### ISSUE TITLE
Empty "Outline" view

### ISSUE THREAD

**Issue by ctron** [eclipse/corrosion#260] opened 2019-07-05 11:57 UTC
I do have the issue that the outline view stays empty now.

<details>
<summary>Language server log</summary>

~~~

[t=1562327704840] LSP4E to org.eclipse.corrosion.rls:
Content-Length: 185



[t=1562327704840] LSP4E to org.eclipse.corrosion.rls:
{"jsonrpc":"2.0","id":"32","method":"textDocument/codeLens","params":{"textDocument":{"uri":"file:///home/XXX/src/http/error.rs"}}}

[t=1562327704840] LSP4E to org.eclipse.corrosion.rls:
Content-Length: 1058



[t=1562327704841] LSP4E to org.eclipse.corrosion.rls:
{"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:///home/XXX/src/http/error.rs","languageId":"rs","version":1,"text":"use core::fmt;\n\nuse esp32_sys::*;\n\nuse cstr_core;\n\n#[derive(Debug)]\npub struct Error {\n    message: \u0026\u0027static str,\n}\n\nimpl fmt::Display for Error {\n    fn fmt(\u0026self, f: \u0026mut fmt::Formatter) -\u003e fmt::Result {\n        self.message.fmt(f)\n    }\n}\n\nimpl From\u003ccstr_core::NulError\u003e for Error {\n    fn from(_e: cstr_core::NulError) -\u003e Self {\n        Error {\n            message: \"Null byte in string\",\n        }\n    }\n}\n\nimpl From\u003cesp_err_t\u003e for Error {\n    fn from(e: esp_err_t) -\u003e Self {\n        Error {\n            message: err_to_str(e),\n        }\n    }\n}\n\nfn err_to_str(err: esp_err_t) -\u003e \u0026\u0027static str {\n    unsafe {\n        let err \u003d esp_err_to_name(err);\n\n        return cstr_core::CStr::from_ptr(err).to_str().unwrap();\n    }\n}\n"}}}

[t=1562327704841] org.eclipse.corrosion.rls to LSP4E:
{"jsonrpc":"2.0","id":"32","result":[]}

[t=1562327705363] LSP4E to org.eclipse.corrosion.rls:
Content-Length: 230



[t=1562327705364] LSP4E to org.eclipse.corrosion.rls:
{"jsonrpc":"2.0","id":"33","method":"textDocument/documentHighlight","params":{"textDocument":{"uri":"file:///home/XXX/src/http/error.rs"},"position":{"line":0,"character":0}}}

[t=1562327705364] org.eclipse.corrosion.rls to LSP4E:
{"jsonrpc":"2.0","id":"33","result":[]}

[t=1562327705370] LSP4E to org.eclipse.corrosion.rls:
Content-Length: 191



[t=1562327705370] LSP4E to org.eclipse.corrosion.rls:
{"jsonrpc":"2.0","id":"34","method":"textDocument/documentSymbol","params":{"textDocument":{"uri":"file:///home/XXX/src/http/error.rs"}}}

[t=1562327705370] org.eclipse.corrosion.rls to LSP4E:
{"jsonrpc":"2.0","id":"34","result":[]}

~~~

</details>

**Comment by mickaelistria** [comment] 2019-07-05 14:13
> {"jsonrpc":"2.0","id":"34","result":[]}

Most likely RLS.

**Comment by akurtakov** [comment] 2019-07-11 13:22
This seems to work fine for me with nightly. Does it for you?

**Comment by norru** [comment] 2019-07-15 08:31
Cannot reproduce either

- latest Corrosion Snapshot
- rls 1.37.0 (124483d 2019-07-01)
- rustc 1.38.0-nightly (83e4eed16 2019-07-14)

**Comment by norru** [comment] 2019-07-15 08:33
However, the layout of the Outline is very ugly, with lots of `__self_*_*` wrappers around struct fields.

**Comment by mickaelistria** [comment] 2019-07-15 08:52
Marked as resolved then.
Please file another ticket for the outline layout and content issues.

**Comment by ctron** [comment] 2019-07-15 09:14
![image](https://user-images.githubusercontent.com/202474/61205980-be353d00-a6f1-11e9-9438-bcbf36c2fbff.png)

**Comment by mickaelistria** [comment] 2019-07-15 09:25
Reopening as per @ctron comment, but I'd really blame RLS here.

**Comment by norru** [comment] 2019-07-15 11:41
@ctron what version of RLS are you on?

**Comment by norru** [comment] 2019-07-15 11:46
https://github.com/eclipse/corrosion/issues/268

**Comment by ctron** [comment] 2019-07-16 06:43
`rls 1.36.0 (9692ca8 2019-05-18)`

**Comment by norru** [comment] 2019-07-16 10:16
I have reproduced the problem with `stable` `rls 1.36.0`.

Upgrading to `rls 1.37` from `nightly` since 2019-07-01 resolves the issue. I don't think there is anything that can be done in Corrosion.

**Comment by ctron** [comment] 2019-07-18 11:30
I do see the technical issue. But from an end user perspective, this is sub-optimal.

Would there be some way of at least showing a note in the outline, indicating a "known issue" with a possible solution.

**Comment by mickaelistria** [comment] 2019-07-18 11:47
> Would there be some way of at least showing a note in the outline,
indicating a "known issue" with a possible solution.

Too much effort for a volatile workaround IMO. It would be more profitable
and a more proper fix to just ask RLS for a newer release.

**Comment by norru** [comment] 2019-07-18 14:33
> indicating a "known issue" with a possible solution.

A "cheap" way of working this around could be to log a warning in the Eclipse Logs stating "RLS returned an empty outline for <file.rs>"

Although, given that the issue is limited to 1.36 and solved in 1.37 it may well be overkill too.

I'll add this to the troubleshooting guide the next time I review it (I need to since the release of 201906).

**Comment by cmcqueen** [comment] 2020-07-02 02:01
I installed Corrosion packages into Eclipse CDT (since I'm already using Eclipse for C/C++) version 2020-03 (4.15.0).

I'm getting syntax highlighting, code analysis. If I do Ctrl-O, I get a quick outline. But the Outline view says "There is no active editor that provides an outline."

The editor that has the Rust file is just "Generic Text Editor". Is there no Rust Editor?

**Comment by mickaelistria** [comment] 2020-07-02 12:10
The Generic Editor contains everything to deal with Rust, so there is no
need for an extra Rust Editor.

**Comment by cmcqueen** [comment] 2020-07-03 01:38
> The Generic Editor contains everything to deal with Rust, so there is no need for an extra Rust Editor.

That's good to have confirmed, thanks. So, why might the Outline view say "There is no active editor that provides an outline" when I've got a Rust file open in the editor?

**Comment by mickaelistria** [comment] 2020-07-03 07:02
It's a bug in Eclipse IDE when multiple adapters can participate to outline; it may not be using the "right" one (eg here it's using an adapter for C/C++ development tools instead of the one for LSP4E which is bound to RLS). This needs to be fixed upstream, or we need a way to make the adapter from LSP4E higher priority in case of Rust.

**Comment by mickaelistria** [comment] 2020-07-03 07:06
Similar issue, with more details and links, exists at https://github.com/eclipse/wildwebdeveloper/issues/294#issuecomment-559823629

**Comment by akurtakov** [comment] 2022-06-02 04:44
Is this one fixed now?

**Comment by mickaelistria** [comment] 2022-06-02 05:48
Yes, fixed in Platform

**Closed by mickaelistria** 2022-06-02 05:48 UTC
Labels: upstream-rls, upstream-eclipse
